# Generated by Django 6.0.1 on 2026-02-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='relation_db.person')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relation_db.tour')),
            ],
        ),
    ]
