# Generated by Django 6.0.1 on 2026-02-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название книги')),
                ('author', models.CharField(max_length=150, verbose_name='автор')),
                ('genre', models.CharField(max_length=150, verbose_name='жанр книги')),
                ('description', models.TextField(verbose_name='описание')),
                ('pages', models.PositiveIntegerField(verbose_name='количество страниц')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='обложка')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('language', models.CharField(max_length=50, verbose_name='язык')),
                ('rating', models.FloatField(verbose_name='рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
