# Generated by Django 6.0.1 on 2026-02-14 10:26

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resume_users/', verbose_name='Фото')),
                ('phone_number', models.CharField(default='+996', max_length=20, verbose_name='Номер телефона')),
                ('gender', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='MALE', max_length=10, verbose_name='Пол')),
                ('city', models.CharField(default='Бишкек', max_length=100, verbose_name='Город')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('skills', models.TextField(verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
